"""
Django settings for projectsite project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
import socket
import sys
from pathlib import Path

DEBUG_ENV = os.environ.get("DEBUG")
RUNNING_DEV_SERVER = any(arg.startswith("runserver") for arg in sys.argv)
if DEBUG_ENV is None:
    # Safe default: production stays False, local runserver stays True.
    DEBUG = RUNNING_DEV_SERVER
else:
    DEBUG = DEBUG_ENV.strip().lower() in {"1", "true", "yes", "on"}

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get(
        "ALLOWED_HOSTS",
        "127.0.0.1,localhost,psusphere.pythonanywhere.com,baterricho.pythonanywhere.com,.pythonanywhere.com",
    ).split(",")
    if host.strip()
]

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get(
        "CSRF_TRUSTED_ORIGINS",
        "http://127.0.0.1,http://localhost,https://baterricho.pythonanywhere.com,https://psusphere.pythonanywhere.com",
    ).split(",")
    if origin.strip()
]

GOOGLE_OAUTH_CLIENT_ID = os.environ.get("GOOGLE_OAUTH_CLIENT_ID", "")
GOOGLE_OAUTH_CLIENT_SECRET = os.environ.get("GOOGLE_OAUTH_CLIENT_SECRET", "")
USE_SETTINGS_GOOGLE_APP_ENV = os.environ.get("USE_SETTINGS_GOOGLE_APP")
if USE_SETTINGS_GOOGLE_APP_ENV is None:
    # If credentials are provided via env, use them automatically.
    USE_SETTINGS_GOOGLE_APP = bool(GOOGLE_OAUTH_CLIENT_ID and GOOGLE_OAUTH_CLIENT_SECRET)
else:
    USE_SETTINGS_GOOGLE_APP = USE_SETTINGS_GOOGLE_APP_ENV.strip().lower() in {"1", "true", "yes", "on"}


def module_available(module_name):
    try:
        __import__(module_name)
        return True
    except ImportError:
        return False


ALLAUTH_ENABLED = module_available("allauth")
WIDGET_TWEAKS_ENABLED = module_available("widget_tweaks")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = "django-insecure-xj%fja1)_)1ywcuy_)8#amn1!#6+)c@vl!3u1i)13avvi^ur@w"


# SECURITY WARNING: don't run with debug turned on in production!
# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "studentorg",
]

if WIDGET_TWEAKS_ENABLED:
    INSTALLED_APPS.append("widget_tweaks")

if ALLAUTH_ENABLED:
    INSTALLED_APPS += [
        "django.contrib.sites",
        "allauth",
        "allauth.account",
        "allauth.socialaccount",
        "allauth.socialaccount.providers.google",
        "allauth.socialaccount.providers.github",
    ]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

if ALLAUTH_ENABLED:
    MIDDLEWARE.insert(
        MIDDLEWARE.index("django.contrib.auth.middleware.AuthenticationMiddleware") + 1,
        "allauth.account.middleware.AccountMiddleware",
    )

ROOT_URLCONF = "projectsite.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "projectsite.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = (
    BASE_DIR / "static",
)

AUTHENTICATION_BACKENDS = ["django.contrib.auth.backends.ModelBackend"]
if ALLAUTH_ENABLED:
    AUTHENTICATION_BACKENDS.append("allauth.account.auth_backends.AuthenticationBackend")

LOGIN_URL = "/admin/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

DEFAULT_SITE_ID = 2 if "pythonanywhere" in socket.gethostname().lower() else 1
SITE_ID = int(os.environ.get("SITE_ID", str(DEFAULT_SITE_ID)))

if ALLAUTH_ENABLED:
    LOGIN_URL = "/accounts/login/"
    LOGOUT_REDIRECT_URL = "/accounts/login/"
    ACCOUNT_LOGOUT_ON_GET = True
    ACCOUNT_LOGOUT_REDIRECT_URL = "/"
    ACCOUNT_LOGIN_METHODS = {"username", "email"}
    ACCOUNT_SIGNUP_FIELDS = ["username*", "email*", "password1*", "password2*"]
    SOCIALACCOUNT_LOGIN_ON_GET = True

    SOCIALACCOUNT_PROVIDERS = {
        "google": {
            "SCOPE": ["profile", "email"],
            "AUTH_PARAMS": {"access_type": "online"},
        }
    }

    if USE_SETTINGS_GOOGLE_APP and GOOGLE_OAUTH_CLIENT_ID and GOOGLE_OAUTH_CLIENT_SECRET:
        SOCIALACCOUNT_PROVIDERS["google"]["APP"] = {
            "client_id": GOOGLE_OAUTH_CLIENT_ID,
            "secret": GOOGLE_OAUTH_CLIENT_SECRET,
            "key": "",
        }

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
